### ISSUE TITLE
README improvements user testing and validation

### ISSUE THREAD

**Issue by antoniivanov** [vmware/versatile-data-kit#2431]
**What is the feature request? What problem does it solve?**

As part of our effort, we plan to redesign our main README.md. 
After we implement the redesign we need to validate if it works 

**Suggested solution**
Usability testing involves observing users as they interact with our system or in this case, our README page.
 The goal is to understand the user experience, identify issues, and gain insights to improve the design. 
 
Scenarios/ task for the usability testing: 

* Scenario 1: Understanding VDK
   * Task 1: Find a brief description of what VDK is.
   * Task 2: Find a list of the key features of VDK.

* Scenario 2: Getting Started with VDK
   * Task 3: Locate the Getting Started instructions. 
   * Task 4: Follow the guide to set up a sample use case
   * Task 5: Find relevant examples or tutorials in the README

* Scenario 3: Seeking Support and Contributing
   * Task 5: Find information on how to get help or support if you run into issues with VDK.
   * Task 6: Identify how you could contribute to the VDK project if you were interested.
 
Note: Remember to remind users to think aloud while performing these tasks, expressing what they understand, what they're looking for, and any challenges they're experiencing

**Additional context**

**Comment by zverulacis** [comment]
Scenario for the call: 

1. Greet, and explain why we are doing this; don't say anything about VDK.
2. Explain the process: 
- There will be 6 questions you need to try to answer
- Think aloud while performing these tasks, expressing what you understand, What are you looking for? Any challenges you're experiencing.
3. Paste the questions: 


Scenario 1: Understanding VDK

Task 1: Find a brief description of what VDK is.
Task 2: Find a list of the key features of VDK.
Scenario 2: Getting Started with VDK

Task 3: Locate the Getting Started instructions.
Task 4: Follow the guide to set up a sample use case
Task 5: Find relevant examples or tutorials in the README
Scenario 3: Seeking Support and Contributing

Task 5: Find information on how to get help or support if you run into issues with VDK.
Task 6: Identify how you could contribute to the VDK project if you were interested.

**Comment by zverulacis** [comment]
1. What is VDK - found super fast vet easy to find 
The very first section - VDK SDK - a framework to simplify ingestion and processing (ONLY SDK) - just data ingestion and processing

2. Key features: are sections the sections - found really fast 
She listed al the sections - Ingestion, all of the sections, she found perfectly
- we can ... 
- load
- transformation
- deployment
- Lego like exper... means modular etc. 

3. Getting started
Less than 3 seconds -getting started, it's in each section
After 10 seconds of scrolling around, found quick-start VDK 

4. Use case - link to the first data job also super fast 
Develop your first data job - I think this is the Hello World version of VDK. 

5. From the readme - examples - each section has examples - get started links if I would want to see the example 

6. For support - contacts, link to join the slack channel, VDK slack channel - I would go there 

7. Contribution - super easy to find 
Example, how to develop and run the application in the development environment 

Dev workflow found 
Guides on testing 
Maybe a list of steps 
How to start dev environment - a page would be nice to have 

Suggestion only for the CONTRIBUTORS guide: 
- Guides on testing 
- Maybe a list of steps 
- How to start dev environment - a page would be nice to have 

All in all pretty good.

**Comment by zverulacis** [comment]
Call with @dakodakov 

- [ ] What is VDK -
   - [ ] I expect to have a description on the top
   - [ ] Versatile data kit Ctrl + F didn't find what is Versatile Data Kit
   - [ ] Checked Wiki - didn't find what is Versatile Data Kit
   - [ ] TOTAL FAIL
- [ ] Documentation not found
- [x] Found features super fast
- [x] Getting started works really well
- [x] Getting started found super fast
- [x] Ingestion use case found pretty fast
- [ ] There's no description of how to create a data job!
- [ ] VDK create is missing in the first ingestion example
   - [ ] He asked will it work without vdk create  I said - NO
- [x] Examples good
- [x] Support - good
- [x] Contributing found:
   - [ ] No table of contents
   - [ ] Security bugs - confusing sentence -
   - [ ] Reverse the order of actions in the sentence about - If you believe you have found a security bug, [create a GitHub issue](https://github.com/vmware/versatile-data-kit/issues) and reach out to us first using any method in the [Contact Us](https://github.com/vmware/versatile-data-kit/blob/main/CONTRIBUTING.md#contact-us) section.

**Comment by zverulacis** [comment]
User testing and validation, DONE
