### ISSUE TITLE
Implement all the improvements from user testing and validation feedback

### ISSUE THREAD

**Issue by antoniivanov** [vmware/versatile-data-kit#2442]
After #2431 we will have list of improvements we want to make to the main README. This story aims to address some of those that are most critical.

**Comment by zverulacis** [comment]
- [ ] VDK about sentence needs to repeat itself in the repo once more
- [ ] Is getting started in the ingestion? Should it be somewhere else?
- [ ] The titles of each section should be as originally intended in Github - on the left
- [ ] The design of the buttons for each section can be improved 
- [ ] If you need SUPPORT - join slack or open an issue
- [ ] first data job or hello world data job
- [ ] write - examples

**Comment by zverulacis** [comment]
PR open: https://github.com/vmware/versatile-data-kit/pull/2654

I will have one more feedback session. Then I'll finalize the changes.

**Comment by zverulacis** [comment]
Todo:

There's no description of how to create a data job!

- [ ] There's no description of how to create a data job! - in the Getting Started guide !

**Comment by zverulacis** [comment]
Open to review. When the PR is merged, the ticket can be closed.
